name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@main
      - run: brew install --cask claude-code
      - run: claude plugin validate .
